- name: Create Gitea data volume
  containers.podman.podman_volume:
    name: gitea_data

- name: Create Gitea config volume
  containers.podman.podman_volume:
    name: gitea_config

- name: Create Gitea Runner config volume
  containers.podman.podman_volume:
    name: gitea_runner_data

- name: Create Gitea Runner data volume
  containers.podman.podman_volume:
    name: gitea_runner_config

- name: Create Gitea network
  containers.podman.podman_network:
    name: gitea_net
    state: present

- name: Create MySQL database for Gitea
  community.mysql.mysql_db:
    name: "{{ gitea_database_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user and grant privileges to Gitea
  community.mysql.mysql_user:
    name: "{{ gitea_database_user }}"
    password: "{{ gitea_database_password }}"
    priv: "{{ gitea_database_name }}.*:ALL"
    state: present
    host: '%'
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Copy runner config to temp file
  template:
    src: templates/runner-config.yml.j2
    dest: /tmp/runner-config.yml

- name: Copy config into podman volume
  command: >
    podman run --rm
      -v gitea_runner_config:/config
      -v /tmp/runner-config.yml:/tmp/config.yml
      alpine
      cp /tmp/config.yml /config/config.yml

- name: Ensure Gitea container is running
  containers.podman.podman_container:
    name: gitea
    image: docker.gitea.com/gitea:1.25.5-rootless
    state: started
    hostname: git.barmin-home.local
    restart_policy: always
    network: gitea_net
    env:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: "host.containers.internal:3306"
      GITEA__database__NAME: "{{ gitea_database_name }}"
      GITEA__database__USER: "{{ gitea_database_user }}"
      GITEA__database__PASSWD: "{{ gitea_database_password }}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "{{ gitea_runner_registration_token }}"
    ports:
      - "3222:3000"
      - "2222:2222"
    volumes:
      - "gitea_data:/var/lib/gitea"
      - "gitea_config:/etc/gitea"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

- name: Create Gitea Actions Runner
  containers.podman.podman_container:
    name: gitea_runner
    image: docker.gitea.com/act_runner:latest
    state: started
    restart_policy: always
    network: gitea_net
    volumes:
      - "gitea_runner_data:/data"
      - "gitea_runner_config:/config"
      - "/run/user/1000/podman/podman.sock:/var/run/user/1000/docker.sock"
    env:
      CONFIG_FILE: /config/config.yml
      DOCKER_HOST: unix:///var/run/user/1000/docker.sock
      GITEA_INSTANCE_URL: http://git.barmin-home.local:3000/
      GITEA_RUNNER_NAME: "Main Runner"
      DOCKERD_ROOTLESS_ROOTLESSKIT_NET: slirp4netns
      DOCKERD_ROOTLESS_ROOTLESSKIT_MTU: 65520
      GITEA_RUNNER_REGISTRATION_TOKEN: "{{ gitea_runner_registration_token }}"

- name: Fix PUBLIC_URL_DETECTION in gitea app.ini without duplicates
  command: >
    podman run --rm
      -v gitea_config:/etc/gitea
      alpine sh -c "
        grep -q '^PUBLIC_URL_DETECTION' /etc/gitea/app.ini || 
        sed -i '/^\[server\]/a PUBLIC_URL_DETECTION = auto' /etc/gitea/app.ini
      "

- name: Register Gitea host in Apache2
  template: 
    src: templates/apache2.conf.j2
    dest: /etc/apache2/sites-available/008-gitea.conf

- name: Enable gitea website in Apache2
  shell: /usr/sbin/a2ensite 008-gitea