version: "3.8"

services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    pid: host
    restart: always
    networks:
      - traefik    
    labels:
      - "traefik.http.routers.glances.rule=Host(`glances.raspberrypi.local`)"
      - "traefik.http.routers.glances.entrypoints=http"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"    
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  traefik:
    external: true
    name: traefik