- name: Create Cloudflared network
  containers.podman.podman_network:
    name: cloudflared_net
    state: present

- name: Ensure Cloudflared container is up and running
  containers.podman.podman_container:
    name: cloudflared
    image: docker.io/cloudflare/cloudflared:latest
    state: started
    restart_policy: always
    network: cloudflared_net
    command:
      - tunnel
      - "--no-autoupdate"
      - "run"
      - "--token"
      - "{{ cloudflared_token }}"
