version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.raspberrypi.local`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  portainer_data:
    name: infra_portainer_data
    external: true

networks:
  traefik:
    external: true
    name: traefik