- name: Install Java 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Add tomcat group
  group:
    name: tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Install Tomcat server
  apt:
    name: tomcat10

- name: Install Tomcat admin app
  apt:
    name: tomcat10-admin

- name: Allow admin access to the admin panel
  template:
    src: templates/tomcat-users.xml.j2
    dest: /etc/tomcat10/tomcat-users.xml

- name: Restart tomcat
  service:
    name: tomcat10
    state: restarted