version: "3.8"

services:
  traefik: 
    image: traefik:v3.3
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    ports:
      - 61208-61209:61208-61209
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    pid: host
    restart: always

  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.raspberrypi.local`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config/homer:/www/assets
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.portainer.rule=Host(`raspberrypi.local`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=8080"

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal
    labels:
      - "traefik.enable=false"

volumes:
  portainer_data:

networks:
  internal: