version: "3.8"

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    pid: host
    restart: always
    networks:
      - traefik    
    labels:
      - "traefik.http.routers.glances.rule=Host(`glances.raspberrypi.local`)"
      - "traefik.http.routers.glances.entrypoints=http"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"    

  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.raspberrypi.local`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./config/homer:/www/assets
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.http.routers.homer.rule=Host(`raspberrypi.local`)"
      - "traefik.http.routers.homer.entrypoints=http"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal
    labels:
      - "traefik.enable=false"

volumes:
  portainer_data:

networks:
  internal:
  traefik:
    external: true
    name: traefik