paperless_database_user: "paperless"
paperless_database_name: "paperless"
paperless_database_password: "paperless_password"

paperless_volume_data: /home/abarmin/podman/paperless_data/
paperless_volume_media: /home/abarmin/podman/paperless_media/
paperless_volume_export: /home/abarmin/podman/paperless_export/
paperless_volume_consume: /home/abarmin/podman/paperless_consume/