- name: Add GPG key Jellyfin
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: jellyfin

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present

- name: Make sure Jellyfin is up and running
  ansible.builtin.systemd:
    name: jellyfin
    enabled: yes
    state: started

- name: Enable apache modules required to proxy requests to jellyfin
  ansible.builtin.command: a2enmod {{ item }}
  loop:
    - proxy
    - proxy_http
    - proxy_wstunnel
    - rewrite
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"

- name: Register jellyfin host in Apache2
  template: 
    src: templates/apache2.conf.j2
    dest: /etc/apache2/sites-available/005-jellyfin.conf

- name: Enable nextcloud website in Apache2
  shell: /usr/sbin/a2ensite 005-jellyfin    
