- name: Add GPG key Jellyfin
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: jellyfin

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present

- name: Make sure Jellyfin is up and running
  ansible.builtin.systemd:
    name: jellyfin
    enabled: yes
    state: started    