- name: Remove existing GoLang installation
  file:
    path: /usr/local/go
    state: absent

- name: Download Golang 1.25.1
  get_url:
    url: https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
    dest: /tmp/go1.25.1.linux-amd64.tar.gz
    mode: '0644'

- name: Extract Golang
  unarchive:
    src: /tmp/go1.25.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
