- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Install PHP
  apt: 
    name: php

- name: Install PHP extensions
  apt:
    name: 
      - libapache2-mod-php
      - php8.3-mbstring
      - php8.3-xml
      - php8.3-zip
      - php8.3-gd
      - php8.3-curl
      - php8.3-gmp
      - php8.3-apcu
      - php8.3-intl
      - php8.3-imagick
      - php8.3-exif    
      - php8.3-redis

- name: Increase PHP memory limit
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: PHP
    option: memory_limit
    value: 2048M
  become: true

- name: Increase PHP upload max file size
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: PHP
    option: upload_max_filesize
    value: 5G
  become: true

- name: Increase PHP POST max size
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: PHP
    option: post_max_size
    value: 5G
  become: true

- name: Disable output buffering
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: PHP
    option: output_buffering
    value: Off
  become: true

- name: Enable opcache
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: opcache
    option: opcache.enable
    value: 1
  become: true

- name: Increase opcache memory consumption
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: opcache
    option: opcache.memory_consumption
    value: 512
  become: true  

- name: Increase opcache string buffer
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: opcache
    option: opcache.interned_strings_buffer
    value: 64
  become: true

- name: Increase opcache max accelerated files
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: opcache
    option: opcache.max_accelerated_files
    value: 50000
  become: true

- name: Increase opcache max wasted percentage
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: opcache
    option: opcache.max_wasted_percentage
    value: 15
  become: true

- name: Increase APC shm size
  ini_file:
    path: /etc/php/8.3/apache2/php.ini
    section: apc
    option: apc.shm_size
    value: 512M
  become: true  

- name: Install MySQL
  apt:
    name: mariadb-server

- name: Set transaction isolation level
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: transaction_isolation
    value: READ-COMMITTED
  become: true

- name: Set binlog format
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: binlog_format
    value: ROW
  become: true   

- name: Make sure MySQL is up and running
  service:
    name: mariadb
    state: started
    enabled: yes

# Uncomment when running for the first time
# - name: Set MySQL root password
#   mysql_user:
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     user: root
#     host_all: yes
#     password: "{{ mysql_root_password }}"
#     priv: "*.*:ALL,GRANT"
#     state: present 

- name: Install MySQL extension for PHP
  apt: 
    name: php-mysql

- name: Install MySQL extension for Python
  apt: 
    name: python3-pymysql

- name: Add PHP Info page
  template: 
    src: templates/phpinfo.php.j2
    dest: /var/www/html/phpinfo.php

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Install Redis
  apt: 
    name: redis

- name: Copy Redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: '0644'

- name: Add redis user to www-group
  user:
    name: redis
    groups: www-data
    append: true
