---
title: "ABarmin Home"
subtitle: "On Raspberry Pi"
logo: "logo.png"

header: false
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

theme: default

message:
  style: "is-dark"
  title: "The work is still in progress"
  icon: "fa fa-grin"
  content: "If you see something that doesn't look right, ask me to fix it."

links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/aabarmin/homelab"
    target: "_blank"
  - name: "BugTracker"
    icon: "fa fa-bug"
    url: "https://bt.abarmin.pro"
    target: "_blank"

services:
  - name: "Management"
    icon: "fas fa-cloud"
    items:
      - name: "Portainer"
        icon: "fa-solid fa-download"
        subtitle: "Docker Container Management"
        tag: "infrastructure"
        url: "http://portainer.raspberrypi.local"
        target: "_blank"
      - name: "Traefik"
        icon: "fa-solid fa-network-wired"
        subtitle: "Reverse Proxy"
        tag: "infrastructure"
        url: "http://raspberrypi.local:8080"
        target: "_blank"
      - name: "Glances"
        icon: "fa-solid fa-server"
        subtitle: "Resource Monitoring"
        tag: "infrastructure"
        url: "http://glances.raspberrypi.local"
        target: "_blank"
  - name: "Hosted Service"
    icon: "fas fa-server"
    items:
      - name: "Mantis Bug Tracker"
        icon: "fa-solid fa-bug"
        subtitle: "Small Bug Tracker"
        tag: "service"
        url: "https://bt.abarmin.pro"
        target: "_blank"
