---
- name: Prepare Intel NUC to work as a home server
  hosts: all
  become: yes
  vars_files:
    - vars/default.yml  
  pre_tasks:
    # - name: Update and upgrade apt packages
    #   apt:
    #     update_cache: yes
    #     upgrade: dist

    - name: Create a directory for the repository
      file:
        path: /home/abarmin/dev
        state: directory
        owner: abarmin
        group: abarmin
        mode: '0755'  

  post_tasks:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted

  roles:
    - lamp
    - phpmyadmin
    - bt-abarmin-pro
    - abarmin-pro
    - nas
    - nfs
    - golang
    - imaginary
    - nextcloud
    - names-publish
    - podman
