---
- name: Install Docker on Raspberry Pi
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      shell: curl -sSL https://get.docker.com | sh

    - name: Add user to Docker group
      user:
        name: abarmin
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create a directory for the repository
      file:
        path: /home/abarmin/dev
        state: directory
        owner: abarmin
        group: abarmin
        mode: '0755'      

    - name: Clone the Git repository with the project
      git:
        repo: https://github.com/aabarmin/homelab.git
        dest: /home/abarmin/dev

    - name: Add a cronjob that publishes subdomains
      ansible.builtin.cron:
        name: "Run Avahi publish"
        job: "/home/abarmin/dev/docker/traefik/publish-names.sh"
        special_time: reboot
        user: "root"