version: "3.8"

services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 64M      
    labels:
      - "traefik.enable=false"

networks:
  internal:
    name: infra_internal
    external: true
  traefik:
    external: true
    name: traefik