version: "3.8"

services:
  traefik: 
    image: traefik:v3.3
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  traefik:
    name: traefik